### ISSUE TITLE
Windows CI not set up

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/autofocus#63]
If and when this project has Windows users, you should set up Appveyor support. To do this, add a file at the repo root called `.appveyor.yml` with this:

```
# How much history do you need from Git?
clone_depth: 5

# Restrict the maximum number of concurrent builds
max_jobs: 10

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:

  matrix:

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - if [%PYTHON_ARCH%]==[32] SET PATH=%MINGW_32%;%PATH% & SET OPENBLAS=%OPENBLAS_32%
  - if [%PYTHON_ARCH%]==[64] SET PATH=%MINGW_64%;%PATH% & SET OPENBLAS=%OPENBLAS_64%

  # Check that we have the expected version and architecture for Python
  - python --version
  - >-
     %CMD_IN_ENV%
     python -c "import sys,platform,struct;
     print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"
  # Install the numpy test dependencies.
  - 'python setup.py install'

build: false

test_script:
  - python -m pytest
```

Then log in to https://ci.appveyor.com/projects with your Github account, click "New Project", and re-enable this repo.
